# Generated by Django 2.0.8 on 2018-08-31 16:45

from django.db import migrations, models
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWordTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Words', separatedvaluesfield.models.SeparatedValuesField(max_length=150)),
            ],
        ),
    ]
