# Generated by Django 2.0.8 on 2018-09-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='jp_word',
            field=models.CharField(max_length=200, verbose_name='日本語訳'),
        ),
    ]
