# Generated by Django 2.0.8 on 2018-09-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180920_2329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
