# Generated by Django 2.0.8 on 2018-09-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='番号')),
                ('en_word', models.CharField(max_length=200, verbose_name='英単語')),
                ('jp_word', models.CharField(max_length=200, verbose_name='日本語訳')),
            ],
            options={
                'verbose_name': '単語',
                'verbose_name_plural': '単語',
            },
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
